name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version (e.g. 3)"
        required: true
        type: string

env:
  REGISTRY: cr.yandex/crplgh0146jj4ahh90mc
  IMAGE_NAME: app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Check image exists
        env:
          YC_OAUTH: ${{ secrets.YC_OAUTH_TOKEN }}
        run: |
          echo "$YC_OAUTH" | yc iam create-token > token.txt
          TOKEN=$(cat token.txt)
          IMAGE_TAG=${{ inputs.release }}_latest

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $TOKEN" \
            "https://container-registry.api.cloud.yandex.net/container-registry/v1/images?registryId=<registry-id>&name=${IMAGE_NAME}&tag=${IMAGE_TAG}")

          if [ "$STATUS" != "200" ]; then
            echo "Image $IMAGE_TAG not found in registry"
            exit 1
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull $REGISTRY/$IMAGE_NAME:${{ inputs.release }}_latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 $REGISTRY/$IMAGE_NAME:${{ inputs.release }}_latest

      - name: Find issue for release
        id: find_issue
        uses: actions/github-script@v7
        with:
          script: |
            const version = "${{ inputs.release }}";
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });

            const issue = issues.find(i => i.title.trim() === `Релиз ${version}`);
            if (!issue) {
              throw new Error(`No issue found for release ${version}`);
            }

            core.setOutput("number", issue.number);

      - name: Get current date
        id: date
        run: echo "value=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Add comment to release issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.find_issue.outputs.number }}
          body: |
            Деплой релиза

            - Дата: ${{ steps.date.outputs.value }}
            - Запустил: @${{ github.actor }}
            - Образ: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.release }}_latest`
